title: Jario Engenheiro Ambiental
logo: /assets/img/jario1.png
background: /assets/img/back.jpg
description: Um engenheiro ambiental é um profissional que atua na área de proteção e conservação do meio ambiente, por meio da aplicação de conhecimentos técnicos, científicos e tecnológicos para minimizar os impactos ambientais causados pelas atividades humanas.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
